version: '3'
services:

  twint:
    build:
      file: Dockerfile.alpine-3.9
      context: .
    container_name: twint
  
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.0.1
    container_name: twint_elasticsearch
    environment:
      - node.name=elasticsearch
      - cluster.initial_master_nodes=elasticsearch
      - cluster.name=docker-cluster
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - esdata01:/usr/share/elasticsearch/data
    ports:
      - 9200:9200

  kibana:
    image: docker.elastic.co/kibana/kibana:7.0.1
    container_name: twint_kibana
    ports:
      - 5601:5601

  relay:
    image: chriswayg/tor-alpine
    container_name: relay
    init: true
    restart: always
    network_mode: host
    environment:
      TOR_NICKNAME: Tor4
      CONTACT_EMAIL: tor4@example.org
    volumes:
      - relay01:/var/lib/tor/
      - ./torrc:/etc/tor/torrc  

volumes:
  esdata01:
    driver: local
  relay01:
    driver: local

networks:
  default:
    external:
      name: nw_twint