---
version: '3.6'
services:

  twint:
    build: .
    container_name: twint
    volumes:
    - './twint:/opt/twint'
    # command: ["-h"]

  searchapp:
    build:
      context: ./searchapp
      dockerfile: Dockerfile
    container_name: searchapp
    ports:
      - 3000:3000
    volumes:
      - './searchapp:/usr/src/app'
      - '/usr/src/app/node_modules'
    environment:
      - NODE_ENV=development

  tor-privoxy:
    restart: always
    container_name: torp
    image: dockage/tor-privoxy:latest
    ports:
    - "9050:9050" # Tor proxy
    - "9051:9051" # Tor control port
    - "8118:8118" # Privoxy
  

  elasticsearch:
    build:
      context: ./elasticsearch
      dockerfile: Dockerfile
      args:
        - CEREBRO_VERSION=0.7.2
    container_name: elasticsearch
    entrypoint: /usr/share/elasticsearch/start
    ports:
      - "9200:9200" # Elasticsearch
      - "9000:9000" # Cerebro
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
     - esdata:/usr/share/elasticsearch/data

  kibana:
    image: docker.elastic.co/kibana/kibana:7.0.1
    container_name: kibana
    ports:
      - 5601:5601

volumes:
  esdata:
    driver: local

networks:
  default:
    external:
      name: nw_twint

      