version: "3"

services:

  #############################
  # TWINT                     #
  #############################
  twint:
    build: .
    container_name: twint
  
  #############################
  # TOR PRIVOXY               #
  #############################  
  tor-privoxy:
    restart: always
    container_name: torp
    image: dockage/tor-privoxy:latest
    ports:
    - "9050:9050" # Tor proxy
    - "9051:9051" # Tor control port
    - "8118:8118" # Privoxy

  #############################
  # ELASTICSEARCH MASTER NODE #
  #############################
  master:
    restart: unless-stopped
    image: blacktop/elasticsearch:7.3
    environment:
      - cluster.name=docker-cluster
      - node.master=true
      - node.ingest=false
      - node.data=false
    volumes:
      - data:/usr/share/elasticsearch/data
    networks:
      - elastic

  ####################################
  # ELASTICSEARCH CLIENT/INGEST NODE #
  ####################################
  ingest:
    restart: unless-stopped
    image: blacktop/elasticsearch:7.3
    environment:
      - cluster.name=docker-cluster
      - node.master=true
      - node.ingest=true
      - node.data=false
      - discovery.zen.ping.unicast.hosts=master
    ports:
      - "9200:9200"
    links:
     - master:elastic-master
    networks:
      - elastic

  ###########################
  # ELASTICSEARCH DATA NODE #
  ###########################
  data:
    restart: unless-stopped
    image: blacktop/elasticsearch:7.3
    environment:
      - ES_JAVA_OPTS=-Xms2g -Xmx2g
      - cluster.name=docker-cluster
      - node.master=false
      - node.ingest=false
      - node.data=true
      - discovery.zen.ping.unicast.hosts=master
    links:
     - master:elastic-master
    # volumes:
    #   - data:/usr/share/elasticsearch/data
    networks:
      - elastic

  ###############
  # KIBANA NODE #
  ###############
  kibana:
    image: blacktop/kibana:7.3
    ports:
      - "80:5601"
    links:
     - ingest:elasticsearch
    networks:
      - elastic

#############################
# ELASTICSEARCH DATA VOLUME #
#############################
volumes:
  data:

################################
# ELASTICSEARCH BRIDGE NETWORK #
################################
networks:
  elastic:
    driver: bridge